// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqAueDzt1ss6c7ZKqcXGBISogUXIxt_8',
    appId: '1:829616481851:web:9d5c454b4280df2e6a1e1e',
    messagingSenderId: '829616481851',
    projectId: 'presensi-pegawai-77e4a',
    authDomain: 'presensi-pegawai-77e4a.firebaseapp.com',
    storageBucket: 'presensi-pegawai-77e4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_DClXWWMwV4BFobQSwwZfK7SvIlZkls',
    appId: '1:829616481851:android:fe4fab72c3a26fb66a1e1e',
    messagingSenderId: '829616481851',
    projectId: 'presensi-pegawai-77e4a',
    storageBucket: 'presensi-pegawai-77e4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7Z8sso8b-D-DrnSWsbPkF8SsKYInv-U',
    appId: '1:829616481851:ios:321a4075d725f8386a1e1e',
    messagingSenderId: '829616481851',
    projectId: 'presensi-pegawai-77e4a',
    storageBucket: 'presensi-pegawai-77e4a.firebasestorage.app',
    iosBundleId: 'com.example.presensiPegawai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7Z8sso8b-D-DrnSWsbPkF8SsKYInv-U',
    appId: '1:829616481851:ios:321a4075d725f8386a1e1e',
    messagingSenderId: '829616481851',
    projectId: 'presensi-pegawai-77e4a',
    storageBucket: 'presensi-pegawai-77e4a.firebasestorage.app',
    iosBundleId: 'com.example.presensiPegawai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqAueDzt1ss6c7ZKqcXGBISogUXIxt_8',
    appId: '1:829616481851:web:636abcd5d4ee47996a1e1e',
    messagingSenderId: '829616481851',
    projectId: 'presensi-pegawai-77e4a',
    authDomain: 'presensi-pegawai-77e4a.firebaseapp.com',
    storageBucket: 'presensi-pegawai-77e4a.firebasestorage.app',
  );
}
